export const ACT_SET_IDE_WIDGET_DRAGIN_OFFSET = `ACT_SET_IDE_WIDGET_DRAGIN_OFFSET`;
export const ACT_UPDATE_IDE_CANVAS_WIDGET_PLACEHOLDER = `ACT_UPDATE_IDE_CANVAS_WIDGET_PLACEHOLDER`;
export const ACT_INSERT_IDE_CANVAS_DRAGING_WIDGET = `ACT_INSERT_IDE_CANVAS_DRAGING_WIDGET`;

