
export const SET_IDE_CODE_TOGGLE = `SET_IDE_CODE_TOGGLE`;
export const SET_IDE_CODE_ACTIVED_TAB = `SET_IDE_CODE_ACTIVED_TAB`;
export const SET_IDE_WIDGET_SELECTED_LIB = `SET_IDE_WIDGET_SELECTED_LIB`;
export const SET_IDE_WIDGET_DRAGING_POSITION = `SET_IDE_WIDGET_DRAGING_POSITION`;
export const DEL_IDE_WIDGET_DRAGING = `DEL_IDE_WIDGET_DRAGING`;
export const SET_IDE_WIDGET_DRAGING = `SET_IDE_WIDGET_DRAGING`;
export const SET_IDE_CANVAS_DRAGING_WIDGET_PREVIEW = `SET_IDE_CANVAS_DRAGING_WIDGET_PREVIEW`;
export const SET_IDE_CANVAS_DRAGING_WIDGET = `SET_IDE_CANVAS_DRAGING_WIDGET`;
export const SET_IDE_CANVAS_WIDGET_DRAGING_OVER =  `SET_IDE_CANVAS_WIDGET_DRAGING_OVER`;